const fatosInteressantes = [
    "As formigas conseguem levantar até 50 vezes o seu próprio peso.",
    "O DNA humano é 99,9% idêntico em todas as pessoas.",
    "O coração humano bate cerca de 100.000 vezes por dia.",
    "A Lua se afasta da Terra a uma taxa de cerca de 3,8 centímetros por ano.",
    "O som viaja quatro vezes mais rápido na água do que no ar.",
    "O olho humano pode distinguir aproximadamente 10 milhões de cores diferentes.",
    "O corpo humano contém água suficiente para encher cerca de 50 piscinas.",
    "Existem mais estrelas no universo observável do que grãos de areia na Terra.",
    "O golfinho é o segundo animal mais inteligente do mundo, depois do ser humano.",
    "A camada de ozônio ajuda a proteger a vida na Terra dos raios ultravioleta do sol.",
    "O elefante é o único animal que não consegue saltar.",
    "O número Pi (π) é uma constante matemática que nunca termina e nunca se repete.",
    "A luz do Sol leva cerca de 8 minutos e 20 segundos para chegar à Terra.",
    "O mel nunca estraga. Potes de mel com mais de 3000 anos foram encontrados em tumbas egípcias.",
    "O cérebro humano tem capacidade de processamento equivalente a 2,5 petabytes de armazenamento.",
    "O diamante é a substância mais dura encontrada na natureza.",
    "A água cobre cerca de 71% da superfície da Terra.",
    "O Sol é uma estrela anã amarela.",
    "O gelo é menos denso do que a água líquida, por isso flutua.",
    "O olfato é o único sentido que não passa pelo tálamo do cérebro antes de chegar ao córtex.",
    "A girafa tem o pescoço composto por apenas sete vértebras, assim como o ser humano.",
    "O planeta Vênus é o mais quente do nosso sistema solar.",
    "A língua é o músculo mais forte do corpo humano em relação ao seu tamanho.",
    "O maior osso do corpo humano é o fêmur, que fica na perna.",
    "O cérebro humano tem cerca de 100 bilhões de neurônios.",
    "A Antártica é o único continente sem população nativa.",
    "O sistema solar tem o nome derivado do latim 'sōlāris', que significa 'do sol'.",
    "O fruto do cacto é chamado de 'figo-da-índia'.",
    "A maior parte do oxigênio da Terra é produzida pelos oceanos, não pelas florestas.",
    "O coala passa a maior parte do tempo dormindo e se alimentando de folhas de eucalipto.",
    "O diamante é uma das formas cristalinas do carbono.",
    "A abelha rainha pode viver até 5 anos, enquanto as abelhas operárias vivem apenas algumas semanas.",
    "Os golfinhos têm nomes próprios e chamam uns aos outros pelo nome.",
    "A maior montanha do mundo, o Monte Everest, tem cerca de 8.848 metros de altura.",
    "A Grande Muralha da China tem mais de 21.000 quilômetros de extensão.",
    "A velocidade da luz é de aproximadamente 299.792.458 metros por segundo.",
    "A maior parte do ouro do mundo está nas profundezas dos oceanos.",
    "Apenas uma em cada duas bilhões de pessoas vive 116 anos ou mais.",
    "A neve não é branca, mas sim transparente. A sua cor é resultado da reflexão da luz solar.",
    "Os elefantes são conhecidos por terem excelente memória e podem se lembrar de eventos por muitos anos.",
    "A camada externa da pele humana é composta por cerca de 30.000 a 40.000 células mortas.",
    "As baleias-azuis são os maiores animais existentes no planeta, podendo chegar a mais de 30 metros de comprimento.",
    "O continente africano é o lar de mais de mil diferentes grupos étnicos.",
    "O maior lago de água doce do mundo em volume é o Lago Baikal, na Rússia.",
    "As formigas são capazes de resolver problemas complexos em grupo.",
    "O crocodilo é o animal que possui a mordida mais poderosa do reino animal.",
    "A Lua é o único objeto celeste fora da Terra onde os humanos já estiveram.",
    "O maior deserto do mundo é o Deserto do Saara, na África.",
    "O maior oceano do mundo é o Oceano Pacífico, abrangendo cerca de 63 milhões de quilômetros quadrados.",
    "A Floresta Amazônica é a maior floresta tropical do mundo e abriga milhões de espécies de plantas e animais.",
    "O veneno da abelha melífera é capaz de aliviar os sintomas de artrite.",
    "Os tigres têm listras únicas, assim como as impressões digitais humanas.",
    "A tartaruga marinha pode viver mais de 100 anos.",
    "As árvores produzem oxigênio através de um processo chamado fotossíntese.",
    "A Ilha de Páscoa é famosa por suas estátuas de pedra chamadas moais.",
    "O albatroz é a ave com maior envergadura de asas, podendo atingir até 3,5 metros.",
    "Os cangurus são capazes de saltar grandes distâncias, chegando a até 13 metros de comprimento e 3 metros de altura.",
    "A borboleta monarca faz uma migração anual de até 4.800 quilômetros.",
    "A geleira de sangue, localizada na Antártica, é uma das mais vermelhas do mundo devido à presença de algas.",
    "A vitamina D é única, pois o corpo humano pode produzi-la quando a pele é exposta à luz solar.",
    "O narval, uma espécie de baleia, possui um longo dente em espiral que pode atingir até 3 metros de comprimento.",
    "A maior flor do mundo, a Rafflesia arnoldii, pode medir até um metro de diâmetro e pesar cerca de 11 quilogramas.",
    "As abelhas são responsáveis pela polinização de aproximadamente um terço dos alimentos que consumimos.",
    "A Grande Barreira de Corais, na Austrália, é o maior sistema de recifes de coral do mundo.",
    "O pinguim-imperador é a única espécie de pinguim que vive exclusivamente na Antártica.",
    "A Baleia-azul possui o som mais alto produzido por um animal, podendo ser ouvida a mais de 800 quilômetros de distância.",
    "Os ursos polares possuem uma camada de gordura de até 11 centímetros de espessura para se isolarem do frio.",
    "O falcão-peregrino é a ave mais rápida do mundo, atingindo velocidades de até 320 quilômetros por hora em um mergulho.",
    "A pele dos elefantes é extremamente sensível ao sol, por isso eles tomam banhos de lama para se protegerem dos raios solares.",
    "O veneno da vespa tem uma substância chamada melitina, que possui propriedades analgésicas e anti-inflamatórias.",
    "A baleia-jubarte é conhecida por seus cantos complexos e melódicos, que podem ser ouvidos a quilômetros de distância.",
    "A truta-arco-íris é capaz de ajustar sua cor para se camuflar em diferentes ambientes aquáticos.",
    "O lobo é um animal altamente social e vive em grupos chamados alcateias.",
    "O camaleão é capaz de mover seus olhos de forma independente, permitindo que ele observe dois ambientes diferentes ao mesmo tempo.",
    "O polvo possui três corações e sangue azul."
    ]

    module.exports = fatosInteressantes